config/routes.rb
Rails.application.routes.draw do

  root 'pages#welcome'

  get '/location', to: 'pages#location', as: 'location'
  get '/gallery', to: 'pages#gallery', as: 'gallery'
  get '/chef-mirko', to: 'pages#chef', as: 'chef'

end

app/models/room.rb
class Room < ActiveRecord::Base

  def getImages
    fullPath = Dir.glob("app/assets/images/rooms/#{self.id}/*.jpg")
    logger.info fullPath
    images = fullPath.map{|path| path.split('/').last.split('.').first}.sort
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def welcome
		@rooms = Room.all.order(:number)
	end

	def location
	end

	def gallery
		@images = Dir.glob("app/assets/images/gallery/*.jpg")
	end

	def chef
		@images = Dir.glob("app/assets/images/chef/*.jpg")
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_class?(test_path)
    request.path == test_path ? 'active' : ''
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-XPXEM4HDSS"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-XPXEM4HDSS');
</script>

  <title>Casa El Paraíso Official Page | Bungalow rooms for rent in Las Galeras, Dominican Republic</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" %>
  <%= stylesheet_link_tag "https://cdn.jsdelivr.net/lightgallery/1.3.7/css/lightgallery.min.css" %>
  <%= javascript_include_tag "https://cdn.jsdelivr.net/g/lightgallery,lg-thumbnail" %>
  <%= csrf_meta_tags %>
  <%= metamagic %>
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <meta name="google-site-verification" content="JDx05ra1ffZaNraIv-5dPBWn_oz2a1QG4gNgUhQJL7k" />


</head>
<body>
  <header class=<%= "fixed" if !current_page?(root_path) %>>
    <nav>
      <label for="hamburger">&#9776; Menu</label>
      <input type="checkbox" id="hamburger"/>

    <ul>
      <li><%= link_to 'Home', root_path, class: current_class?(root_path) %></li>
      <li><%= link_to 'Gallery', gallery_path, class: current_class?(gallery_path) %></li>
      <li><%= link_to 'Chef Mirko', chef_path, class: current_class?(chef_path) %></li>
      <li><%= link_to 'Location', location_path, class: current_class?(location_path) %></li>
    </div>
    </nav>
    <%= link_to image_tag("el-paraiso.png", alt: 'Casa El Paraiso. Bungalow rooms for rent in Las Galeras'), '/' %>
  </header>
  <%= yield %>

  <!-- Google Analytics -->
	<script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

	ga('create', 'UA-90317567-1', 'auto');
	ga('send', 'pageview');
	</script>

  <div id="whatsapp">
    <a href="https://api.whatsapp.com/send?phone=34607018258", target="_blank">
  </div>
</body>
</html>

app/views/pages/chef.html.haml
- meta description: "Chef Mirko Casagrande at Casa El Paraiso", keywords: %w(ecolodge bungalow samana las galeras guazuma dominican republic villa paraiso rent room airbnb travel vacations republica dominicana paradise mirko chef house)

#content
  #chef
    .wrapper
      .left
        #mirko
          = image_tag 'mirko.jpg', alt: 'Chef Mirko'
          %p Hi, I'm <strong>Chef Mirko</strong>. 
          %p I invite you to enjoy an unforgettable, rustic culinary experience @ El Paraiso. 
          %p All of my dishes use high quality fresh ingredients, both local and imported.
        #mirko-mentions
          %h6 Mentions through Airbnb Reviews
          .mention
            .user
              .photo
                %img{:src=> "https://a0.muscache.com/im/pictures/d839dbbc-86fb-4249-a759-44d088096a5a.jpg?aki_policy=profile_x_medium"}
              .name Sheridan
            .text 
              [...] I cannot recommend enough reserving a meal with Mirko. It was exceptional. We had a seafood pasta followed by grilled lobster and we could not believe how good it was. Treat yourself. 
              .date July 2019
          .mention
            .user
              .photo
                %img{:src=> "https://a0.muscache.com/im/pictures/46d8a1c0-2001-4780-a797-5ef92e8fff09.jpg?aki_policy=profile_x_medium"}
              .name  Natalie
            .text 
              [...] We also could try out the cooking abilities of Mirko. Yes he is an amazing cook so that we never went out for dinner. Thank Mirko for your outstanding angus beef. [...]
              .date April 2019
          .mention
            .user
              .photo
                %img{:src=> "https://a0.muscache.com/im/pictures/user/d69dbadb-d813-450d-bc08-c5a32bc04092.jpg?aki_policy=profile_x_medium"}
              .name  David
            .text 
              [...] We had the pleasure of having Chef Mirko cook dinner for us, and let me tell you, you must not pass up this opportunity. Food was delicious. [...]
              .date February 2019
      .right
        .masonry
          - @images.each do |image|
            - image = image.split('/').last
            .item 
              = link_to image_tag("chef/#{image}", alt: image.split('.').first ), asset_path("chef/#{image}"), class: 'thumbnail'
        

app/views/pages/directions.html.haml
#content

  #directions
    %h2 Location

    .wrapper
      .left
        #address
          = image_tag('icons/location.png')
          %p La Guazuma, Samana Province </br>Dominican Republic
          = link_to 'Navigate in Google Maps', 'https://goo.gl/maps/UDwEjiMEHcaUvQ3v9', target: '_blank'
      #map
        %iframe{:src => "https://www.google.com/maps/d/u/0/embed?mid=1vyAEwNh31f9YBoQgJOhtW_D9HCzbGDVq", :width => "100%", :height => "400", :frameborder => "0"}

app/views/pages/gallery.html.haml
#content
  #gallery
    .wrapper
      .masonry
        - @images.each do |image|
          - image = image.split('/').last
          .item 
            = link_to image_tag("gallery/#{image}", alt: image.split('.').first ), asset_path("gallery/#{image}"), class: 'thumbnail'

app/views/pages/location.html.haml
#content

  #directions
    %h2 Location

    .wrapper
      .left
        #address
          = image_tag('icons/location.png')
          %p La Guazuma Street</br>Las Galeras, Samaná </br>Dominican Republic
          = link_to 'Navigate in Google Maps', 'https://www.google.com/maps/dir//Casa+El+Para%C3%ADso,+Calle+subida,+Las+Galeras+32000,+Dominican+Republic/@19.2450817,-69.1970488,16.03z/data=!4m9!4m8!1m0!1m5!1m1!1s0x8eaedc9cae51d90f:0x5d88f193ebe3aa84!2m2!1d-69.1974555!2d19.251785!3e0?entry=ttu', target: '_blank'
      #map
        %iframe{:src => "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3766.7026878647052!2d-69.20003042307088!3d19.25178498198944!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8eaedc9cae51d90f%3A0x5d88f193ebe3aa84!2sCasa%20El%20Para%C3%ADso!5e0!3m2!1sen!2ses!4v1706010907950!5m2!1sen!2ses", :width => "100%", :height => "400", :frameborder => "0"}

app/views/pages/welcome.html.haml
- meta description: "El Paraíso is a top rated ecolodge getaway with amazing ocean views. It's truly a unique way to experience the Dominican Republic and its natural beauty.", keywords: %w(ecolodge bungalow samana las galeras guazuma dominican republic villa paraiso rent room airbnb travel vacations republica dominicana paradise las terrenas house)

#hero
  #overlay
    .slide.first
      /= image_tag "rooms/5/2.jpg", alt: 'Room view', rel: "preload"
      #headline
        %h1 Ocean view rooms for rent
        %h2
          /= image_tag 'icons/geo.png', alt: 'Las Galeras, Samana'
          Top rated airbnb in Dominican Republic
        = link_to 'See the rooms', "#rooms", id: 'cta'

#content

  #description
    .wrapper

      .item
        .item-image.left
          = link_to image_tag("rooms/1/thumbnails/1.jpg", alt: 'Ocean-view bungalow rooms for rent.'), asset_path("rooms/1/1.jpg")
        .item-description
          %h3.item-title A one-of-a-kind experience
          %p.item-text "El Paraíso" is a rustic getaway situated atop cliffs overlooking beautiful Samana Bay. It offers private bungalow rooms perfect for couples with a series of activities nearby including zip lines, whale watching, diving and more.

      .item
        .item-image.right
          = link_to image_tag("immerse-yourself.jpg", alt: 'The pool with ocean-view.'), asset_path("immerse-yourself.jpg")
        .item-description
          %h3.item-title Immerse yourself in nature
          %p.item-text Constructed from local materials that blend into the surrounding ecosystem, its a place where you can immerse yourself in nature, find tranquility and connect with your inner self and your beloved ones.

  #strip

    = link_to image_tag("thumbnails/deck.jpg", alt: 'Deck area.'), asset_path("deck.jpg"), class: 'thumbnail'
    = link_to image_tag("thumbnails/pool-view.jpg", alt: 'Pool sunset view.'), asset_path('pool-view.jpg'), class: 'thumbnail'
    = link_to image_tag("thumbnails/sunbed.jpg", alt: 'Sun bed.'), asset_path('sunbed.jpg'), class: 'thumbnail'
    = link_to image_tag("thumbnails/social-area.jpg", alt: 'Social area.'), asset_path('social-area.jpg'), class: 'thumbnail'
    = link_to image_tag("thumbnails/hosts.jpg", alt: 'Hosts: Nora & Jose.'), asset_path('hosts.jpg'), class: 'thumbnail'

  #rooms
    .wrapper
      %div
        %h2 Our Rooms
        #big-group
          Big group?
          = link_to 'Rent the Villa', "https://www.airbnb.com/rooms/12092507?s=67&shared_item_type=1&virality_entry_point=1", target: '_blank'

      = form_tag('/search', remote: true, id: 'availability') do

        %em Check Availability:
        = label_tag :checkin, 'Check In'
        = text_field_tag :checkin, '', class: 'datepicker', placeholder: 'dd/mm/yyyy'

        = label_tag :checkout, 'Check Out'
        = text_field_tag :checkout, '', class: 'datepicker', placeholder: 'dd/mm/yyyy'

        = submit_tag 'Search Dates', type: :submit

      %ul
        - @rooms.each do |r|
          %li.room
            .room-images
              - r.getImages.each do |image|
                = link_to image_tag("rooms/#{r.number}/thumbnails/#{image}.jpg", alt: ''), asset_path("rooms/#{r.number}/#{image}.jpg")
            .room-number Room ##{r.number}
            .room-price USD $#{"%.2f" % r.price}
            %ul.room-info
              %li
                = image_tag('icons/guest.png')
                #{r.capacity} guests
              %li
                = image_tag('icons/bed.png')
                #{r.beds} bed
              %li
                = image_tag('icons/size.png')
                #{r.size}m<sup>2</sup>
              %li
                = image_tag('icons/bathroom.png')
                #{r.bathrooms} bathroom

            .room-desc
              %p
                = r.description
                /%span= image_tag "icons/airbnb_stars"
                = link_to 'Book now through Airbnb', "https://www.airbnb.com/rooms/#{r.airbnb_id}?s=67&shared_item_type=1&virality_entry_point=1", class: 'book', target: '_blank'

  #parallax
    %span Immerse yourself in nature
    = video_tag ["parallax.mp4"], :controls => false, :muted => "muted", :autoplay => "autoplay", :loop => "loop", :preload => 'none', width: "100%", height: "auto"

  #airbnb-reviews
    .wrapper{ style: "position: relative"}
      %script{src:"https://apps.elfsight.com/p/platform.js", async:"true", defer:"true"}
      %div.elfsight-app-02504cae-b997-4cbb-bb55-93f5a31367bd
      = link_to 'See all', 'https://www.airbnb.com/users/60995700/listings', target:'_blank'

  #services
    /%h2 Additional Services
    /%ul.wrapper
    /%li Breakfast <span>(included)</span>
    /%li Housekeeping <span>(included)</span>
    /%li Bar
    /%li Dominican Cook
    /%li Catamaran Excursion
    /%li Dinner by Chef Mirko

app/views/welcome/index.html.haml
- meta description: "El Paraíso is an ecolodge getaway with ocean-view overlooking Samana Bay. It's truly a unique way to experience the Dominican Republic and its natural beauty.", keywords: %w(ecolodge bungalow samana las galeras guazuma dominican republic villa paraiso rent room airbnb travel vacations republica dominicana paradise las terrenas house)

#hero
  #overlay
    #superhost
    .slide.first
      #headline 
        %h1 Villa & Bungalow rooms for rent
        %h2 
          = image_tag 'icons/geo.png', alt: 'Las Galeras, Samana'
          Las Galeras, Dominican Republic
        = link_to 'See the rooms', "#rooms", id: 'cta'
    .slide.second
      = video_tag ["samana.mp4","samana.ogv"], :controls => false, :autoplay => "autoplay", :loop => "loop", :preload => 'auto'
    %button.w3-button.w3-display-left{ :onclick=> "plusDivs(-1)" }
      &#10094;
    %button.w3-button.w3-display-right{ :onclick=> "plusDivs(+1)"} 
      &#10095;

#reviews
  = link_to '', 'https://www.marieclaire.com/travel/g27243755/airbnb-casa-el-paraiso-dominican-republic/?utm_medium=social-media&utm_source=facebook&utm_campaign=socialflowFBMAR', id: 'marie-claire', target: "_blank"

  = link_to '', 'https://www.lonelyplanet.com/dominican-republic/las-galeras/hotels/casa-el-paraiso/a/lod/e2779545-1004-4c8f-92ee-968b21cc34c8/358033', id: 'lonely-planet', target: "_blank" 

  = link_to '', 'https://www.housebeautiful.com/lifestyle/g26949434/airbnb-casa-el-paraiso-dominican-republic/', id: 'house-beautiful', target: "_blank" 

  = link_to '', 'https://www.hoppingaroundtheglobeinstyle.com/paradise-found-bunnys-review-of-villa-paraiso-in-las-galeras-dominican-republic/', id: 'bunnys', target: "_blank" 


#content

  #description.wrapper

    .item
      .item-image.left
        = link_to image_tag("rooms/thumbnails/room-1.jpg", alt: 'Ocean-view bungalow rooms for rent.'), asset_path("rooms/room-1.jpg")
      .item-description
        %h3.item-title A one-of-a-kind experience
        %p.item-text "El Paraíso" is a rustic getaway situated atop cliffs overlooking Samana Bay. Constructed from natural and local materials, it's truly a one-of-a-kind way to experience the Dominican Republic and its natural beauty.

    .item
      .item-image.right
        = link_to image_tag("thumbnails/pool.jpg", alt: 'The pool with ocean-view.'), asset_path("pool.jpg")
      .item-description
        %h3.item-title Immerse yourself in nature
        %p.item-text Surrounded by tropical gardens and overall amazing views, its a very special place where you can immerse yourself in nature, find tranquility and connect with your inner self and your beloved ones.



  #expand click images to expand
  #gallery

    = link_to image_tag("thumbnails/living-room-entrance.jpg", alt: 'Living room entrance.'), asset_path("living-room-entrance.jpg"), class: 'thumbnail'
    = link_to image_tag("thumbnails/dinner-table.jpg", alt: 'Dinner table.'), asset_path('dinner-table.jpg'), class: 'thumbnail'
    = link_to image_tag("thumbnails/pool-pov.jpg", alt: 'Pool.'), asset_path('pool-pov.jpg'), class: 'thumbnail'
    = link_to image_tag("thumbnails/poolside-bar.jpg", alt: 'Poolside bar.'), asset_path('poolside-bar.jpg'), class: 'thumbnail'
    = link_to image_tag("thumbnails/poolside-area.jpg", alt: 'Poolside area.'), asset_path('poolside-area.jpg'), class: 'thumbnail'

  #rooms
    .wrapper
      %h2 Rooms.
      %span Available for rent via Airbnb.
      #big-group
        Big group?
        =link_to 'Rent the Villa', "#villa"

      = form_tag('/search', remote: true, id: 'availability') do

        %em Check Availability:
        = label_tag :checkin, 'Check In'
        = text_field_tag :checkin, '', class: 'datepicker', placeholder: 'dd/mm/yyyy'

        = label_tag :checkout, 'Check Out'
        = text_field_tag :checkout, '', class: 'datepicker', placeholder: 'dd/mm/yyyy'

        = submit_tag 'Search Dates', type: :submit

    - @rooms.each do |r|
      .room
        .wrapper
          .room-number ##{r.number}
          .room-images
            = link_to image_tag("rooms/thumbnails/room-#{r.number}.jpg", alt: ''), asset_path("rooms/room-#{r.number}.jpg")
            = link_to image_tag("rooms/thumbnails/room-#{r.number}-view.jpg", alt: ''), asset_path("rooms/room-#{r.number}-view.jpg")
            = link_to image_tag("rooms/thumbnails/room-#{r.number}-bathroom.jpg", alt: ''), asset_path("rooms/room-#{r.number}-bathroom.jpg")
          %ul.room-info
            %li
              = image_tag('icons/guest.png')
              #{r.capacity} guests
            %li
              = image_tag('icons/bed.png')
              #{r.beds} bed
            %li
              = image_tag('icons/size.png')
              #{r.size}m<sup>2</sup>
            %li
              = image_tag('icons/bathroom.png')
              #{r.bathrooms} bathroom

          .room-desc
            %p
              = r.description
              /%span= image_tag "icons/airbnb_stars"
              = link_to 'Book now through Airbnb', "https://www.airbnb.com/rooms/#{r.airbnb_id}", class: 'book', target: '_blank'

  #villa
    .wrapper
      %h2 Rent the Villa.
      %span Ideal for big families or groups.

      .room
        .wrapper
          .room-number
          .room-images
            = link_to image_tag("thumbnails/living-room-entrance.jpg", alt: 'Living room entrance.'), asset_path("living-room-entrance.jpg"), class: 'thumbnail'
          %ul.room-info
            %li
              = image_tag('icons/guest.png')
              15 guests
            %li
              = image_tag('icons/bed.png')
              9 beds
            %li
              = image_tag('icons/size.png')
              5700m<sup>2</sup>
            %li
              = image_tag('icons/bathroom.png')
              7 bathrooms

          .room-desc
            %p
              All five open-design bungalow rooms and one studio room with air conditioning to accomodate your whole group.
              = link_to 'Book now through Airbnb', "https://www.airbnb.com/rooms/12092507", class: 'book', target: '_blank'


  #services
    %h2 Additional Services
    %ul.wrapper
      %li Breakfast <span>(included)</span>
      %li Housekeeping <span>(included)</span>
      %li Bar
      %li Dominican Cook
      %li Picnic Baskets
      %li Yoga Session
      %li Reiki Session
      %li Catamaran Excursion
      %li Dinner by Chef Mirko

  #location
    %h2 Location

    #map.wrapper
      %iframe{:src => "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1205829.7240267175!2d-69.89551042944235!3d19.250776892870743!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x5a3d9ac3f3a6ec7f!2sCasa+El+Paraiso!5e0!3m2!1sen!2ses!4v1483461678445", :width => "100%", :height => "500", :frameborder => "0"}


  #media
    .wrapper 
      /%h2 Media
      /%iframe{:width => "100%", :height => "500", :src=> "https://www.youtube.com/embed/1oi4DoBWpTw", :frameborder=> "0", :allow=> "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"}
      /%p Credit: <a href="https://www.hoppingaroundtheglobeinstyle.com" target="_blank">https://www.hoppingaroundtheglobeinstyle.com</a>